### ISSUE TITLE
Error while reading data from cargo-flamegraph

### ISSUE THREAD

**Issue by Paulo-21** [YS-L/flamelens#2]
Hello, I love your project
I encountered an error when i  would like to visualize the data generate by cargo-flamegraph 
![image](https://github.com/YS-L/flamelens/assets/34631206/68b48062-f601-4972-829b-9a3e33f6c3e3)
Any idea ?

**Comment by YS-L** [comment]
Hi! `perf.data` is the profiling data generated by perf, but currently the supported input format for `flamelens`  is collapsed stack data. It can be obtained this way using a tool from the [inferno](https://crates.io/crates/inferno) crate:

```
perf script -i perf.data | inferno-collapse-perf | flamelens
```

**Comment by Paulo-21** [comment]
It work perfectly for me, it would be nice to link this issue in the readme like 
"If you use cargo-flamegraph basicly you can check this " ?
